Repository jenkins-x/go-scm, pull requests merged in 2019-10, with the labels that each got.

#33 fix: avoid failures on bitbucket cluster
  scm/driver/bitbucket/issue.go
  scm/driver/bitbucket/issue_test.go
  scm/factory/examples/pr/main.go
Labels: approved, lgtm, size/L

#34 fix: add support for get PRs to bitbucket cloud
  README.md
  go.mod
  scm/driver/bitbucket/pr.go
  scm/driver/bitbucket/pr_test.go
  scm/driver/bitbucket/repo.go
  scm/driver/bitbucket/repo_test.go
  scm/driver/bitbucket/testdata/pulls.json
  scm/driver/bitbucket/testdata/pulls.json.golden
  scm/driver/bitbucket/testdata/repo.json.golden
  scm/driver/bitbucket/testdata/repos.json.golden
  scm/driver/bitbucket/user.go
  scm/factory/examples/pr/main.go
  scm/factory/factory.go
Labels: approved, lgtm, size/XL

#35 fix: add a bitbucket cloud FindRef method
  scm/driver/bitbucket/git.go
  scm/driver/bitbucket/testdata/ref.json
  scm/driver/bitbucket/util.go
Labels: approved, lgtm, size/XXL

#37 fix: add support for GitHub Apps
  scm/app.go
  scm/client.go
  scm/driver/github/app.go
  scm/driver/github/github.go
  scm/driver/github/testdata/webhooks/installation.json
  scm/driver/github/testdata/webhooks/installation.json.golden
  scm/driver/github/webhook.go
  scm/driver/github/webhook_test.go
  scm/webhook.go
Labels: approved, lgtm, size/L

#38 fix: add support for passing the GitHub App installation header
  scm/driver/github/testdata/webhooks/installation.json.golden
  scm/driver/github/testdata/webhooks/issue_comment.json
  scm/driver/github/testdata/webhooks/issue_comment.json.golden
  scm/driver/github/webhook.go
  scm/webhook.go
Labels: approved, size/L

#39 fix: add support for ping webhook
  scm/driver/github/testdata/webhooks/ping.json
  scm/driver/github/testdata/webhooks/ping.json.golden
  scm/driver/github/webhook.go
  scm/driver/github/webhook_test.go
  scm/webhook.go
Labels: approved, size/L

#40 fix: missing installation ID
  scm/driver/github/testdata/webhooks/installation.json
  scm/driver/github/testdata/webhooks/installation.json.golden
  scm/driver/github/testdata/webhooks/installation_delete.json
  scm/driver/github/testdata/webhooks/installation_delete.json.golden
  scm/driver/github/webhook.go
  scm/driver/github/webhook_test.go
  scm/webhook.go
Labels: approved, size/L

#41 fix: add a webhook kind
  scm/webhook.go
Labels: size/M

#36 Fix GitHub CombinedStatus implementation.
  scm/driver/github/repo.go
  scm/driver/github/repo_test.go
  scm/driver/github/testdata/combined_status.json
  scm/driver/github/testdata/combined_status.json.golden
Labels: approved, lgtm, ok-to-test, size/L

#42 fix: add support for the account and install links
  scm/driver/github/testdata/webhooks/installation.json.golden
  scm/driver/github/testdata/webhooks/installation_delete.json.golden
  scm/driver/github/webhook.go
  scm/webhook.go
Labels: approved, size/S

#44 fix: updatebot changes for downstream PRs
  jenkins-x.yml
  updatebot.sh
Labels: approved, size/XS

#45 fix: updatebot PR
  updatebot.sh
Labels: approved, size/XS

#43 fix; Add JSON marshalling support for State codes.
  scm/const.go
  scm/driver/bitbucket/testdata/status.json.golden
  scm/driver/bitbucket/testdata/statuses.json.golden
  scm/driver/gitea/testdata/status.json.golden
  scm/driver/gitea/testdata/statuses.json.golden
  scm/driver/github/testdata/combined_status.json.golden
  scm/driver/github/testdata/status.json.golden
  scm/driver/github/testdata/statuses.json.golden
  scm/driver/gitlab/testdata/status.json.golden
  scm/driver/gitlab/testdata/statuses.json.golden
  scm/driver/stash/testdata/commit_build_status.json.golden
Labels: approved, lgtm, ok-to-test, size/M

#47 fix: Add fake implementation for Status operations.
  scm/driver/fake/data.go
  scm/driver/fake/repo.go
Labels: approved, lgtm, ok-to-test, size/M

#46 fix: json.Marshal for State.
  scm/const.go
  scm/const_test.go
Labels: approved, lgtm, ok-to-test, size/M
