Repository jenkins-x/go-scm, pull requests merged in 2019-09, with the labels that each got.

#24 fix: Add Bitbucket Server commit build status query
  scm/driver/stash/repo.go
  scm/driver/stash/repo_test.go
  scm/driver/stash/testdata/commit_build_status.json
  scm/driver/stash/testdata/commit_build_status.json.golden
Labels: approved, lgtm, ok-to-test, size/L

#25 fix: fix use of branch/ref and sha in PullRequestHook
  scm/driver/gitlab/testdata/webhooks/pull_request_close.json.golden
  scm/driver/gitlab/testdata/webhooks/pull_request_create.json.golden
  scm/driver/gitlab/testdata/webhooks/pull_request_merge.json.golden
  scm/driver/gitlab/testdata/webhooks/pull_request_reopen.json.golden
  scm/driver/gitlab/webhook.go
  scm/driver/stash/pr.go
  scm/driver/stash/testdata/pr.json.golden
  scm/driver/stash/testdata/prs.json.golden
  scm/driver/stash/testdata/webhooks/pr_comment.json.golden
  scm/driver/stash/testdata/webhooks/pr_declined.json.golden
  scm/driver/stash/testdata/webhooks/pr_merged.json.golden
  scm/driver/stash/testdata/webhooks/pr_open.json.golden
  scm/driver/stash/webhook.go
Labels: approved, lgtm, size/M

#26 fix: automate PR to update lighthouse
  jenkins-x.yml
Labels: size/XS

#23 fix: typos in sample program
  scm/factory/examples/repos/main.go
Labels: approved, lgtm, ok-to-test, size/XS

#27 fix: lets use the version env var instead
  jenkins-x.yml
Labels: size/XS

#22 fix: Add GitHub PullRequest Labels
  scm/driver/github/pr.go
  scm/driver/github/testdata/pr.json
  scm/driver/github/testdata/pr.json.golden
  scm/driver/github/testdata/webhooks/pr_labeled.json.golden
  scm/pr.go
Labels: approved, lgtm, size/M

#29 fix: add another example program + add GraphQL api
  go.mod
  go.sum
  scm/client.go
  scm/const.go
  scm/driver/bitbucket/issue.go
  scm/driver/fake/issue.go
  scm/driver/gitea/issue.go
  scm/driver/github/github.go
  scm/driver/github/issue.go
  scm/driver/github/issue_test.go
  scm/driver/github/pr.go
  scm/driver/github/testdata/issue_search.json
  scm/driver/github/testdata/issue_search.json.golden
  scm/driver/github/testdata/issue_search_prs.json
  scm/driver/github/testdata/issue_search_prs.json.golden
  scm/driver/github/testdata/pr.json
  scm/driver/github/testdata/pr.json.golden
  scm/driver/github/testdata/pulls.json.golden
  scm/driver/github/util.go
  scm/driver/gitlab/issue.go
  scm/driver/gogs/issue.go
  scm/driver/stash/issue.go
  scm/factory/examples/graphql/main.go
  scm/factory/examples/pr/main.go
  scm/factory/examples/search/main.go
  scm/factory/factory.go
  scm/issue.go
  scm/pr.go
Labels: approved, lgtm, size/XXL

#32 fix: github enterprise graphql endpoint url
  scm/client.go
  scm/driver/github/github.go
  scm/driver/github/github_test.go
Labels: approved, lgtm, ok-to-test, size/M
