Repository jenkins-x/go-scm, pull requests merged in 2019-11, with the labels that each got.

#48 fix: add API to query an App repository installation
  scm/app.go
  scm/driver/github/app.go
  scm/driver/github/app_test.go
  scm/driver/github/testdata/app_repo_install.json
  scm/driver/github/testdata/app_repo_install.json.golden
  scm/driver/github/testdata/webhooks/installation.json.golden
  scm/driver/github/testdata/webhooks/installation_delete.json.golden
  scm/driver/github/webhook.go
  scm/driver/github/webhook_test.go
  scm/webhook.go
Labels: approved, size/L

#50 feat: add function to get installations for an organisation
  scm/app.go
  scm/driver/github/app.go
Labels: approved, lgtm, size/M

#49 feat: Implement CreateStatus, return PR labels in fake.
  scm/driver/fake/pr.go
  scm/driver/fake/repo.go
Labels: approved, lgtm, ok-to-test, size/S

#52 fix: add support for more webhooks
  scm/const.go
  scm/driver/github/testdata/webhooks/check_run_created.json
  scm/driver/github/testdata/webhooks/check_run_created.json.golden
  scm/driver/github/testdata/webhooks/check_suite_created.json
  scm/driver/github/testdata/webhooks/check_suite_created.json.golden
  scm/driver/github/testdata/webhooks/deployment_status.json
  scm/driver/github/testdata/webhooks/deployment_status.json.golden
  scm/driver/github/testdata/webhooks/label_deleted.json
  scm/driver/github/testdata/webhooks/label_deleted.json.golden
  scm/driver/github/testdata/webhooks/status.json
  scm/driver/github/testdata/webhooks/status.json.golden
  scm/driver/github/webhook.go
  scm/driver/github/webhook_test.go
  scm/webhook.go
Labels: approved, size/XXL

#53 fix: add support for release webhooks
  scm/driver/github/testdata/webhooks/release.json
  scm/driver/github/testdata/webhooks/release.json.golden
  scm/driver/github/webhook.go
  scm/driver/github/webhook_test.go
  scm/webhook.go
Labels: approved, size/L

#54 feat: Add support for Label CRUD for Gitlab.
  scm/driver/bitbucket/pr.go
  scm/driver/fake/data.go
  scm/driver/fake/pr.go
  scm/driver/gitea/pr.go
  scm/driver/gitlab/issue.go
  scm/driver/gitlab/pr.go
  scm/driver/gitlab/repo.go
  scm/driver/gogs/pr.go
  scm/driver/stash/pr.go
  scm/pr.go
Labels: approved, lgtm, ok-to-test, size/L

#57 fix: Switch PR comments to be stored separately from issue comments.
  scm/driver/fake/pr.go
Labels: approved, lgtm, ok-to-test, size/S

#58 chore: add Dan to owners
  OWNERS
Labels: approved, size/XS

#56 feat(tests): add PR build tests
  jenkins-x.yml
Labels: approved, size/S

#59 fix: added a few more webhooks
  scm/driver/github/testdata/webhooks/fork.json
  scm/driver/github/testdata/webhooks/fork.json.golden
  scm/driver/github/testdata/webhooks/installation_repository.json
  scm/driver/github/testdata/webhooks/installation_repository.json.golden
  scm/driver/github/testdata/webhooks/repository.json
  scm/driver/github/testdata/webhooks/repository.json.golden
  scm/driver/github/webhook.go
  scm/driver/github/webhook_test.go
  scm/webhook.go
Labels: approved, size/XL
