Repository jenkins-x/go-scm, pull requests merged in 2020-04, with the labels that each got.

#86 feat: Add support for factory options.
  scm/factory/factory.go
  scm/factory/factory_test.go
Labels: approved, lgtm, ok-to-test, size/S

#88 feat: mock for github org list
  scm/driver/fake/org.go
Labels: approved, lgtm, size/S

#89 feat: gitlab comments hooks & pull request labels support
  scm/driver/gitlab/pr.go
  scm/driver/gitlab/repo.go
  scm/driver/gitlab/testdata/pr_create.json.golden
  scm/driver/gitlab/testdata/webhooks/pull_request_comment_create.json
  scm/driver/gitlab/testdata/webhooks/pull_request_comment_create.json.golden
  scm/driver/gitlab/webhook.go
  scm/driver/gitlab/webhook_test.go
Labels: approved, lgtm, ok-to-test, size/L

#90 Make github driver return scm.ErrNotFound.
  scm/driver/github/github.go
Labels: approved, lgtm, size/XS

#87 chore: Add a bunch of GitLab API functionality
  scm/const.go
  scm/driver/bitbucket/git.go
  scm/driver/bitbucket/issue.go
  scm/driver/bitbucket/org.go
  scm/driver/bitbucket/pr.go
  scm/driver/bitbucket/repo.go
  scm/driver/fake/pr.go
  scm/driver/gitea/git.go
  scm/driver/gitea/issue.go
  scm/driver/gitea/org.go
  scm/driver/gitea/pr.go
  scm/driver/gitea/repo.go
  scm/driver/github/integration/github_test.go
  scm/driver/github/integration/issue_test.go
  scm/driver/github/integration/pr_test.go
  scm/driver/github/org.go
  scm/driver/gitlab/git.go
  scm/driver/gitlab/gitlab.go
  scm/driver/gitlab/issue.go
  scm/driver/gitlab/issue_test.go
  scm/driver/gitlab/pr.go
  scm/driver/gitlab/pr_test.go
  scm/driver/gitlab/repo.go
  scm/driver/gitlab/repo_test.go
  scm/driver/gitlab/testdata/combined_status.json.golden
  scm/driver/gitlab/testdata/issue.json.golden
  scm/driver/gitlab/testdata/issue_events.golden.json
  scm/driver/gitlab/testdata/issue_events.json
  scm/driver/gitlab/testdata/issues.json.golden
  scm/driver/gitlab/testdata/pr_events.golden.json
  scm/driver/gitlab/testdata/pr_events.json
  scm/driver/gitlab/testdata/project_member_perm.json
  scm/driver/gitlab/testdata/statuses.json
  scm/driver/gitlab/testdata/statuses.json.golden
  scm/driver/gitlab/user.go
  scm/driver/gogs/git.go
  scm/driver/gogs/issue.go
  scm/driver/gogs/org.go
  scm/driver/gogs/pr.go
  scm/driver/gogs/repo.go
  scm/driver/stash/git.go
  scm/driver/stash/issue.go
  scm/driver/stash/org.go
  scm/driver/stash/pr.go
  scm/driver/stash/repo.go
  scm/issue.go
  scm/pr.go
  scm/repo.go
Labels: approved, size/XXL

#91 fix: Handle BitBucket Server "pr:from_ref_updated" hook
  scm/driver/fake/org.go
  scm/driver/gitlab/pr.go
  scm/driver/gitlab/webhook.go
  scm/driver/gitlab/webhook_test.go
  scm/driver/stash/testdata/webhooks/pr_ref_updated.json
  scm/driver/stash/testdata/webhooks/pr_ref_updated.json.golden
  scm/driver/stash/webhook.go
  scm/driver/stash/webhook_test.go
Labels: approved, size/L

#92 fix: Handle GH PR ready_for_review events properly
  scm/const.go
  scm/driver/github/testdata/webhooks/pr_ready_for_review.json
  scm/driver/github/testdata/webhooks/pr_ready_for_review.json.golden
  scm/driver/github/webhook.go
  scm/driver/github/webhook_test.go
Labels: approved, size/XL

#93 feat: Configurable fake organizations.
  scm/driver/fake/data.go
  scm/driver/fake/org.go
Labels: approved, lgtm, size/M

#94 feat: update permissions data
  scm/driver/github/org.go
Labels: approved, lgtm, size/XS

#97 fix: Add mergeable/mergeable state handling for GitLab
  scm/driver/github/org.go
  scm/driver/gitlab/pr.go
  scm/driver/gitlab/testdata/merge.json.golden
  scm/driver/gitlab/testdata/merges.json.golden
  scm/driver/gitlab/testdata/pr_create.json.golden
  scm/pr.go
Labels: approved, size/M

#98 chore: Add some more GitHub hooks
  scm/driver/github/webhook.go
  scm/driver/github/webhook_test.go
  scm/review.go
  scm/webhook.go
Labels: approved, size/L

#99 fix: Allow specifying GitHub merge method
  scm/driver/bitbucket/pr.go
  scm/driver/fake/pr.go
  scm/driver/gitea/pr.go
  scm/driver/gitea/pr_test.go
  scm/driver/github/pr.go
  scm/driver/github/pr_test.go
  scm/driver/github/testdata/pr_merge.json
  scm/driver/github/util.go
  scm/driver/gitlab/pr.go
  scm/driver/gitlab/pr_test.go
  scm/driver/gogs/pr.go
  scm/driver/gogs/pr_test.go
  scm/driver/stash/pr.go
  scm/driver/stash/pr_test.go
  scm/example_test.go
  scm/pr.go
Labels: approved, size/M

#100 feat: add isAdmin method to org api for github
  scm/driver/bitbucket/org.go
  scm/driver/fake/org.go
  scm/driver/gitea/org.go
  scm/driver/github/org.go
  scm/driver/github/org_test.go
  scm/driver/github/testdata/membership_admin.json
  scm/driver/github/testdata/membership_member.json
  scm/driver/gitlab/org.go
  scm/driver/gogs/org.go
  scm/driver/stash/org.go
  scm/org.go
Labels: approved, lgtm, size/L

#101 chore: Run integration tests for GL and GH in PR build
  jenkins-x.yml
  scm/driver/gitlab/integration/content_test.go
  scm/driver/gitlab/integration/issue_test.go
  scm/driver/gitlab/integration/pr_test.go
Labels: approved, size/S

#102 test: add org isAdmin fake implementation
  scm/driver/fake/org.go
Labels: approved, lgtm, size/XS

#103 feat: Add listing org members
  scm/driver/bitbucket/org.go
  scm/driver/fake/org.go
  scm/driver/gitea/org.go
  scm/driver/github/org.go
  scm/driver/github/org_test.go
  scm/driver/github/testdata/org_members.json
  scm/driver/github/testdata/org_members.json.golden
  scm/driver/gitlab/org.go
  scm/driver/gogs/org.go
  scm/driver/stash/org.go
  scm/org.go
Labels: approved, size/L

#104 feat: Add EditComment to issues and PRs
  scm/driver/bitbucket/issue.go
  scm/driver/fake/issue.go
  scm/driver/fake/pr.go
  scm/driver/gitea/issue.go
  scm/driver/gitea/pr.go
  scm/driver/github/issue.go
  scm/driver/github/issue_test.go
  scm/driver/github/testdata/edit_issue_comment.json
  scm/driver/gitlab/gitlab.go
  scm/driver/gitlab/issue.go
  scm/driver/gitlab/issue_test.go
  scm/driver/gitlab/pr.go
  scm/driver/gitlab/pr_test.go
  scm/driver/gitlab/testdata/edit_issue_note.json
  scm/driver/gogs/issue.go
  scm/driver/gogs/pr.go
  scm/driver/stash/issue.go
  scm/driver/stash/pr.go
  scm/issue.go
  scm/pr.go
Labels: approved, size/L

#106 fix: Handle GitHub IsMember/IsCollaborator 404s properly
  scm/driver/github/org.go
  scm/driver/github/org_test.go
  scm/driver/github/repo.go
  scm/driver/github/repo_test.go
Labels: approved, size/M

#107 feat: Add labels and update/create times to GitLab PR listing
  scm/const.go
  scm/driver/gitlab/integration/pr_test.go
  scm/driver/gitlab/pr_test.go
  scm/driver/gitlab/testdata/merges.json
  scm/driver/gitlab/testdata/merges.json.golden
  scm/driver/gitlab/util.go
  scm/pr.go
Labels: approved, size/M

#108 chore: Add name field to BitBucket Cloud commit status creation
  scm/driver/bitbucket/repo.go
  scm/driver/bitbucket/repo_test.go
  scm/driver/bitbucket/testdata/status_input.json
Labels: approved, size/XS

#109 fix: Set description on GitLab commit statuses
  scm/driver/gitlab/repo.go
Labels: approved

#110 fix: Use GitLab's work-in-progress as draft value
  scm/driver/gitlab/pr.go
  scm/driver/gitlab/testdata/merge.json
  scm/driver/gitlab/testdata/merge.json.golden
Labels: approved, size/XS

#111 fix: Include state on GitLab PRs
  scm/driver/gitlab/pr.go
  scm/driver/gitlab/testdata/merge.json.golden
  scm/driver/gitlab/testdata/merges.json.golden
  scm/driver/gitlab/testdata/pr_create.json.golden
Labels: approved, size/XS

#112 fix: PR state on GitLab webhooks, issue state as well.
  scm/driver/gitlab/integration/pr_test.go
  scm/driver/gitlab/issue.go
  scm/driver/gitlab/pr.go
  scm/driver/gitlab/testdata/issue.json.golden
  scm/driver/gitlab/testdata/issues.json.golden
  scm/driver/gitlab/testdata/merge.json.golden
  scm/driver/gitlab/testdata/merges.json.golden
  scm/driver/gitlab/testdata/pr_create.json.golden
  scm/driver/gitlab/testdata/webhooks/pull_request_close.json.golden
  scm/driver/gitlab/testdata/webhooks/pull_request_comment_create.json.golden
  scm/driver/gitlab/testdata/webhooks/pull_request_create.json.golden
  scm/driver/gitlab/testdata/webhooks/pull_request_merge.json.golden
  scm/driver/gitlab/testdata/webhooks/pull_request_reopen.json.golden
  scm/driver/gitlab/util.go
  scm/driver/gitlab/webhook.go
Labels: approved, size/L

#113 fix: Get full user list for permissions check on GitLab
  scm/driver/gitlab/repo.go
  scm/driver/gitlab/repo_test.go
Labels: approved

#114 fix: Shouldn't include "refs/heads/" in GitLab MR base/target refs
  scm/driver/gitlab/pr.go
  scm/driver/gitlab/testdata/merge.json.golden
  scm/driver/gitlab/testdata/merges.json.golden
  scm/driver/gitlab/testdata/pr_create.json.golden
Labels: approved, size/S

#115 fix: Edited GitLab MR should be an update action, not a sync
  scm/driver/gitlab/testdata/webhooks/pull_request_edited.json
  scm/driver/gitlab/testdata/webhooks/pull_request_edited.json.golden
  scm/driver/gitlab/webhook.go
  scm/driver/gitlab/webhook_test.go
Labels: approved, size/L
