Repository jenkins-x/go-scm, pull requests merged in 2020-05, with the labels that each got.

#116 fix: Add ListOptions to ListCollaborators
  scm/driver/bitbucket/repo.go
  scm/driver/fake/repo.go
  scm/driver/gitea/repo.go
  scm/driver/github/repo.go
  scm/driver/gitlab/repo.go
  scm/driver/gitlab/repo_test.go
  scm/driver/gogs/repo.go
  scm/driver/stash/repo.go
  scm/factory/examples/contributors/main.go
  scm/repo.go
Labels: approved, size/M

#117 fix: Return everything for page 0 _or_ size 0 in fake
  scm/driver/fake/utils.go
Labels: approved, size/XS

#119 fix: Add support for requesting and unrequesting reviews
  scm/driver/bitbucket/pr.go
  scm/driver/fake/pr.go
  scm/driver/gitea/pr.go
  scm/driver/github/pr.go
  scm/driver/github/pr_test.go
  scm/driver/github/testdata/delete_reviewers.json
  scm/driver/github/testdata/delete_reviewers_pr.json
  scm/driver/github/testdata/request_reviewers.json
  scm/driver/gitlab/pr.go
  scm/driver/gogs/pr.go
  scm/driver/stash/pr.go
  scm/pr.go
Labels: approved, size/XL

#120 fix: Include ID in GitLab user transformation
  scm/driver/gitlab/testdata/contributors.json.golden
  scm/driver/gitlab/testdata/issue_events.golden.json
  scm/driver/gitlab/testdata/pr_events.golden.json
  scm/driver/gitlab/testdata/user.json.golden
  scm/driver/gitlab/testdata/user_search.json.golden
  scm/driver/gitlab/user.go
Labels: approved, size/S

#121 fix: Include assignees in GL MR info, and use IDs there.
  scm/driver/gitlab/pr.go
  scm/driver/gitlab/testdata/merge.json
  scm/driver/gitlab/testdata/merge.json.golden
  scm/driver/gitlab/testdata/merges.json.golden
  scm/driver/gitlab/testdata/pr_create.json.golden
Labels: approved, size/M

#122 fix: Need to specify 0 as assignee id when removing all existing ones from GitLab
  scm/driver/gitlab/pr.go
Labels: approved, size/XS

#118 fix: Fake client to create hook with generated ID and delete hook by ID.
  scm/driver/fake/data.go
  scm/driver/fake/repo.go
  scm/driver/fake/repo_test.go
Labels: approved, lgtm, ok-to-test, size/M

#123 chore: Add a number of BitBucket Server implementations
  scm/driver/stash/pr.go
  scm/driver/stash/pr_test.go
  scm/driver/stash/repo.go
  scm/driver/stash/repo_test.go
  scm/driver/stash/testdata/combined_status.json.golden
  scm/driver/stash/testdata/commit_build_status.json
  scm/driver/stash/testdata/commit_build_status.json.golden
  scm/driver/stash/testdata/find_user_permission.json
Labels: approved, size/L

#124 fix: Add Version to scm.Comment
  scm/driver/stash/pr.go
  scm/driver/stash/pr_test.go
  scm/driver/stash/testdata/pr_comment.json
  scm/driver/stash/testdata/pr_comment.json.golden
  scm/issue.go
Labels: approved, size/S

#125 fix: BBS edit comment needs version
  scm/driver/stash/pr.go
  scm/driver/stash/pr_test.go
Labels: approved, size/M

#126 chore: Add separate reviewers field to scm.PullRequest
  scm/driver/github/pr.go
  scm/driver/github/testdata/pr_create.json.golden
  scm/driver/stash/pr.go
  scm/driver/stash/testdata/pr.json
  scm/driver/stash/testdata/pr.json.golden
  scm/pr.go
Labels: approved, size/L

#127 fix: Add issue/PR Reopen function
  scm/driver/bitbucket/issue.go
  scm/driver/bitbucket/pr.go
  scm/driver/fake/issue.go
  scm/driver/fake/pr.go
  scm/driver/gitea/issue.go
  scm/driver/gitea/pr.go
  scm/driver/github/issue.go
  scm/driver/github/issue_test.go
  scm/driver/github/pr.go
  scm/driver/github/pr_test.go
  scm/driver/github/testdata/close.json
  scm/driver/github/testdata/reopen.json
  scm/driver/gitlab/issue.go
  scm/driver/gitlab/issue_test.go
  scm/driver/gitlab/pr.go
  scm/driver/gitlab/pr_test.go
  scm/driver/gogs/issue.go
  scm/driver/gogs/pr.go
  scm/driver/stash/issue.go
  scm/driver/stash/pr.go
  scm/driver/stash/pr_test.go
  scm/issue.go
  scm/pr.go
Labels: approved, size/L

#128 feat: Implement GitHub create/update of a repository file.
  scm/content.go
  scm/driver/github/content.go
  scm/driver/github/content_test.go
  scm/driver/github/testdata/content.json.golden
Labels: approved, lgtm, ok-to-test, size/M

#129 feat: Add support for creating new refs in GitHub.
  scm/driver/bitbucket/git.go
  scm/driver/fake/git.go
  scm/driver/gitea/git.go
  scm/driver/github/git.go
  scm/driver/github/git_test.go
  scm/driver/github/testdata/ref.json
  scm/driver/github/testdata/ref.json.golden
  scm/driver/gitlab/git.go
  scm/driver/gogs/git.go
  scm/driver/stash/git.go
  scm/git.go
Labels: approved, lgtm, ok-to-test, size/M

#130 chore: Add GOPROXY to release pipeline
  OWNERS
  jenkins-x.yml
Labels: approved, size/XS

#131 fix: Properly fetch/handle BitBucket Server PR comment listing
  scm/driver/stash/pr.go
  scm/driver/stash/pr_test.go
  scm/driver/stash/testdata/pr_comments.json
  scm/driver/stash/testdata/pr_comments.json.golden
Labels: approved, size/L

#132 feat: Add updating of pull requests
  scm/driver/bitbucket/pr.go
  scm/driver/fake/pr.go
  scm/driver/gitea/pr.go
  scm/driver/github/pr.go
  scm/driver/github/pr_test.go
  scm/driver/github/testdata/pr_update.json
  scm/driver/gitlab/pr.go
  scm/driver/gitlab/pr_test.go
  scm/driver/gitlab/testdata/pr_update.json
  scm/driver/gogs/pr.go
  scm/driver/stash/pr.go
  scm/driver/stash/pr_test.go
  scm/driver/stash/testdata/pr_update.json
  scm/pr.go
Labels: approved, size/L

#133 fix: Add pr:modified hook for BitBucket Server
  scm/driver/stash/testdata/webhooks/pr_modified.json
  scm/driver/stash/testdata/webhooks/pr_modified.json.golden
  scm/driver/stash/webhook.go
  scm/driver/stash/webhook_test.go
Labels: approved, size/L

#134 fix: Include ref in BBS PRs, fix latest commit for base as well
  scm/driver/stash/pr.go
  scm/driver/stash/testdata/pr.json.golden
  scm/driver/stash/testdata/prs.json.golden
  scm/driver/stash/testdata/webhooks/pr_comment.json.golden
  scm/driver/stash/testdata/webhooks/pr_declined.json.golden
  scm/driver/stash/testdata/webhooks/pr_merged.json.golden
  scm/driver/stash/testdata/webhooks/pr_modified.json.golden
  scm/driver/stash/testdata/webhooks/pr_open.json.golden
  scm/driver/stash/testdata/webhooks/pr_ref_updated.json.golden
  scm/driver/stash/webhook.go
  scm/driver/stash/webhook_test.go
Labels: approved, size/L

#135 fix: Implement IsAdmin for BitBucket Server
  scm/driver/stash/org.go
Labels: approved, size/S

#136 feat: support for github's add collaborator api
  scm/driver/bitbucket/repo.go
  scm/driver/fake/repo.go
  scm/driver/gitea/repo.go
  scm/driver/github/repo.go
  scm/driver/github/repo_test.go
  scm/driver/github/testdata/add_collaborator.json
  scm/driver/gitlab/repo.go
  scm/driver/gogs/repo.go
  scm/driver/stash/repo.go
  scm/repo.go
Labels: approved, lgtm, size/L

#137 fix: Add BBS ListOrgMembers and tests for IsAdmin/IsMember
  scm/driver/stash/org.go
  scm/driver/stash/org_test.go
  scm/driver/stash/testdata/org_members.json
  scm/driver/stash/testdata/org_members.json.golden
Labels: approved, size/L

#138 fix: Pass PR version to BitBucket Server PR merge
  scm/driver/stash/pr.go
  scm/driver/stash/pr_test.go
Labels: approved, size/S

#139 fix: Disable XSRF check on BitBucket Server
  scm/driver/stash/stash.go
Labels: approved, size/XS

#140 refactor: add extra return bool to AddCollaborator to indicate if use…
  scm/driver/bitbucket/repo.go
  scm/driver/fake/repo.go
  scm/driver/gitea/repo.go
  scm/driver/github/repo.go
  scm/driver/github/repo_test.go
  scm/driver/gitlab/repo.go
  scm/driver/gogs/repo.go
  scm/driver/stash/repo.go
  scm/repo.go
Labels: approved, lgtm, size/M

#141 feat: add AddCollaborator fake implementation
  scm/driver/fake/repo.go
  scm/factory/factory.go
Labels: approved, lgtm, size/S

#142 feat: Implement CreateRef and CreateContent for GitLab.
  scm/driver/gitlab/content.go
  scm/driver/gitlab/content_test.go
  scm/driver/gitlab/git.go
  scm/driver/gitlab/git_test.go
  scm/driver/gitlab/testdata/create_branch.json
  scm/driver/gitlab/testdata/create_branch.json.golden
Labels: approved, lgtm, size/L

#143 feat: Use constant-time comparison for the GitLab token.
  scm/driver/gitlab/webhook.go
Labels: approved, lgtm, size/XS

#144 fix: GH review approval action fix, PR review hooks for BBS
  scm/const.go
  scm/driver/github/repo_test.go
  scm/driver/github/testdata/webhooks/pr_review_submitted.json
  scm/driver/github/testdata/webhooks/pr_review_submitted.json.golden
  scm/driver/github/webhook.go
  scm/driver/github/webhook_test.go
  scm/driver/stash/testdata/webhooks/pr_approved.json
  scm/driver/stash/testdata/webhooks/pr_approved.json.golden
  scm/driver/stash/testdata/webhooks/pr_needs_work.json
  scm/driver/stash/testdata/webhooks/pr_needs_work.json.golden
  scm/driver/stash/testdata/webhooks/pr_unapproved.json
  scm/driver/stash/testdata/webhooks/pr_unapproved.json.golden
  scm/driver/stash/webhook.go
  scm/driver/stash/webhook_test.go
Labels: approved, size/XXL

#145 fix: Reviews service was just comments
  scm/driver/bitbucket/review.go
  scm/driver/fake/review.go
  scm/driver/gitea/review.go
  scm/driver/github/review.go
  scm/driver/github/review_test.go
  scm/driver/github/testdata/reviews_create.json
  scm/driver/github/testdata/reviews_dismiss.json
  scm/driver/github/testdata/reviews_find.json
  scm/driver/github/testdata/reviews_find.json.golden
  scm/driver/github/testdata/reviews_list.json
  scm/driver/github/testdata/reviews_list.json.golden
  scm/driver/github/testdata/reviews_list_comments.json
  scm/driver/github/testdata/reviews_list_comments.json.golden
  scm/driver/github/testdata/reviews_submit.json
  scm/driver/github/testdata/reviews_update.json
  scm/driver/github/testdata/webhooks/pr_review_submitted.json.golden
  scm/driver/github/webhook.go
  scm/driver/gitlab/review.go
  scm/driver/gogs/review.go
  scm/driver/stash/review.go
  scm/example_test.go
  scm/review.go
Labels: approved, size/XL
