Repository jenkins-x/go-scm, pull requests merged in 2020-08, with the labels that each got.

#162 feat: Adding GraphQL for gitlab
  go.mod
  scm/driver/gitlab/gitlab.go
Labels: approved, lgtm, ok-to-test, size/M

#163 chore: Add Patch field to scm.Change
  scm/driver/github/pr.go
  scm/driver/github/testdata/changes.json.golden
  scm/driver/github/testdata/pr_files.json.golden
  scm/driver/gitlab/pr.go
  scm/driver/gitlab/testdata/commit_diff.json.golden
  scm/driver/gitlab/testdata/merge_diff.json.golden
  scm/pr.go
Labels: approved, size/S

#165 feat: Add repo AddCollaborator and Create PR for BitBucket Server
  scm/driver/stash/org.go
  scm/driver/stash/pr.go
  scm/driver/stash/pr_test.go
  scm/driver/stash/repo.go
  scm/driver/stash/repo_test.go
  scm/driver/stash/testdata/add_collaborator.json
  scm/driver/stash/testdata/find_user_permission.json
Labels: approved, size/L
