Repository jenkins-x/go-scm, pull requests merged in 2020-07, with the labels that each got.

#152 feat: Add support for adding collaborators to repos in GitLab
  scm/driver/gitlab/repo.go
  scm/driver/gitlab/repo_test.go
  scm/driver/gitlab/testdata/add_collaborator.json
  scm/driver/gitlab/testdata/add_collaborator_user.json
Labels: approved, size/M

#153 fix: Implement repo creation for GitLab and BitBucket Server
  scm/driver/gitlab/gitlab.go
  scm/driver/gitlab/org.go
  scm/driver/gitlab/repo.go
  scm/driver/gitlab/repo_test.go
  scm/driver/gitlab/testdata/create_project.json
  scm/driver/gitlab/testdata/find_namespace.json
  scm/driver/gitlab/testdata/group.json.golden
  scm/driver/gitlab/testdata/groups.json.golden
  scm/driver/stash/repo.go
  scm/driver/stash/repo_test.go
  scm/driver/stash/testdata/create_repo.json
Labels: approved, size/L

#154 feat: Add Fork to repository service
  scm/driver/bitbucket/repo.go
  scm/driver/fake/repo.go
  scm/driver/gitea/repo.go
  scm/driver/github/repo.go
  scm/driver/github/repo_test.go
  scm/driver/github/testdata/repo_fork_input.json
  scm/driver/gitlab/repo.go
  scm/driver/gitlab/repo_test.go
  scm/driver/gitlab/testdata/fork_project.json
  scm/driver/gogs/repo.go
  scm/driver/stash/repo.go
  scm/driver/stash/repo_test.go
  scm/driver/stash/testdata/fork_repo.json
  scm/repo.go
  updatebot.sh
Labels: approved, lgtm, size/L

#155 fix: add support for content to fake
  scm/driver/fake/content.go
  scm/driver/fake/content_test.go
  scm/driver/fake/data.go
  scm/driver/fake/fake.go
  scm/driver/fake/test_data/myorg/myrepo/README.md
  scm/driver/fake/test_data/myorg/myrepo/somedir/something.txt
Labels: approved, lgtm, size/L

#156 feat: Add list/accept repo invites for user
  scm/driver/bitbucket/user.go
  scm/driver/fake/user.go
  scm/driver/gitea/user.go
  scm/driver/github/testdata/list_invitations.json
  scm/driver/github/testdata/list_invitations.json.golden
  scm/driver/github/user.go
  scm/driver/github/user_test.go
  scm/driver/gitlab/user.go
  scm/driver/gogs/user.go
  scm/driver/stash/user.go
  scm/user.go
Labels: approved

#157 feat: Automatically identify the driver from a URL.
  scm/factory/drivers.go
  scm/factory/drivers_test.go
  scm/factory/factory.go
  scm/factory/factory_test.go
Labels: approved, lgtm, size/L

#158 Adds WebhookService constructors and factory
  scm/driver/bitbucket/bitbucket.go
  scm/driver/fake/pr.go
  scm/driver/gitea/gitea.go
  scm/driver/github/github.go
  scm/driver/gitlab/gitlab.go
  scm/driver/gogs/gogs.go
  scm/driver/stash/stash.go
  scm/factory/factory.go
Labels: approved, lgtm, ok-to-test, size/M

#159 fix: Add PreviousPath to scm.Change
  scm/driver/github/pr.go
  scm/driver/gitlab/pr.go
  scm/driver/gitlab/testdata/commit_diff.json.golden
  scm/driver/gitlab/testdata/merge_diff.json.golden
  scm/driver/stash/git.go
  scm/driver/stash/testdata/changes.json.golden
  scm/factory/factory.go
  scm/pr.go
Labels: approved, size/M
