Repository jenkins-x/go-scm, pull requests merged in 2020-09, with the labels that each got.

#167 fix: for GitHub Enterprise
  scm/driver/github/repo.go
Labels: approved, lgtm, size/XS

#168 feat: Switch Gitea to use Gitea's go-sdk client behind the scenes
  go.mod
  go.sum
  scm/driver/gitea/content.go
  scm/driver/gitea/git.go
  scm/driver/gitea/gitea.go
  scm/driver/gitea/issue.go
  scm/driver/gitea/issue_test.go
  scm/driver/gitea/org.go
  scm/driver/gitea/pr.go
  scm/driver/gitea/pr_test.go
  scm/driver/gitea/repo.go
  scm/driver/gitea/repo_test.go
  scm/driver/gitea/testdata/assign_issue.json
  scm/driver/gitea/testdata/close_issue.json
  scm/driver/gitea/testdata/close_pr.json
  scm/driver/gitea/testdata/comment.json
  scm/driver/gitea/testdata/comment.json.golden
  scm/driver/gitea/testdata/comments.json
  scm/driver/gitea/testdata/comments.json.golden
  scm/driver/gitea/testdata/issue.json
  scm/driver/gitea/testdata/issue.json.golden
  scm/driver/gitea/testdata/issue_labels.json
  scm/driver/gitea/testdata/issue_labels.json.golden
  scm/driver/gitea/testdata/issues.json
  scm/driver/gitea/testdata/issues.json.golden
  scm/driver/gitea/testdata/pr.json.golden
  scm/driver/gitea/testdata/pr_create.json
  scm/driver/gitea/testdata/prs.json.golden
  scm/driver/gitea/testdata/reopen_issue.json
  scm/driver/gitea/testdata/reopen_pr.json
  scm/driver/gitea/testdata/repo.json.golden
  scm/driver/gitea/testdata/repos.json.golden
  scm/driver/gitea/testdata/unassign_issue.json
  scm/driver/gitea/testdata/user.json.golden
  scm/driver/gitea/testdata/webhooks/branch_create.json.golden
  scm/driver/gitea/testdata/webhooks/branch_delete.json.golden
  scm/driver/gitea/testdata/webhooks/issue_comment_created.json.golden
  scm/driver/gitea/testdata/webhooks/issues_opened.json.golden
  scm/driver/gitea/testdata/webhooks/pull_request_closed.json.golden
  scm/driver/gitea/testdata/webhooks/pull_request_comment_created.json.golden
  scm/driver/gitea/testdata/webhooks/pull_request_edited.json.golden
  scm/driver/gitea/testdata/webhooks/pull_request_merged.json.golden
  scm/driver/gitea/testdata/webhooks/pull_request_opened.json.golden
  scm/driver/gitea/testdata/webhooks/pull_request_reopened.json.golden
  scm/driver/gitea/testdata/webhooks/pull_request_synchronized.json.golden
  scm/driver/gitea/testdata/webhooks/push.json.golden
  scm/driver/gitea/testdata/webhooks/tag_create.json.golden
  scm/driver/gitea/testdata/webhooks/tag_delete.json.golden
  scm/driver/gitea/user.go
  scm/driver/gitea/webhook.go
  scm/org.go
Labels: approved, lgtm, size/XXL

#169 fix: A number of gitea-related fixes
  scm/driver/gitea/content.go
  scm/driver/gitea/git.go
  scm/driver/gitea/gitea.go
  scm/driver/gitea/issue.go
  scm/driver/gitea/org.go
  scm/driver/gitea/pr.go
  scm/driver/gitea/pr_test.go
  scm/driver/gitea/repo.go
  scm/driver/gitea/testdata/pr.json.golden
  scm/driver/gitea/testdata/pr_changes.json.golden
  scm/driver/gitea/testdata/pr_changes.patch
  scm/driver/gitea/testdata/prs.json.golden
  scm/driver/gitea/testdata/webhooks/pull_request_closed.json.golden
  scm/driver/gitea/testdata/webhooks/pull_request_comment_created.json.golden
  scm/driver/gitea/testdata/webhooks/pull_request_edited.json.golden
  scm/driver/gitea/testdata/webhooks/pull_request_merged.json.golden
  scm/driver/gitea/testdata/webhooks/pull_request_opened.json.golden
  scm/driver/gitea/testdata/webhooks/pull_request_reopened.json.golden
  scm/driver/gitea/testdata/webhooks/pull_request_synchronized.json.golden
  scm/driver/gitea/user.go
  scm/driver/gitea/webhook.go
  scm/driver/gitlab/git.go
  scm/factory/factory.go
Labels: approved, size/XXL

#171 fix: Query/path escape user and ref in BitBucket Server
  scm/driver/stash/content.go
  scm/driver/stash/git.go
  scm/driver/stash/pr.go
  scm/driver/stash/repo.go
  scm/driver/stash/user.go
Labels: approved, size/M

#170 feat: Add review API support for Gitea
  scm/driver/gitea/review.go
  scm/driver/gitea/review_test.go
  scm/driver/gitea/testdata/review.json
  scm/driver/gitea/testdata/review.json.golden
  scm/driver/gitea/testdata/review_create.json
  scm/driver/gitea/testdata/reviews.json
  scm/driver/gitea/testdata/reviews.json.golden
  scm/driver/gitea/testdata/version.json
Labels: approved, size/L

#173 fix: make testing content with refs easier for fake
  scm/driver/fake/content.go
  scm/driver/fake/content_test.go
  scm/driver/fake/test_data/test_refs/myorg/myrepo/README.md
  scm/driver/fake/test_data/test_refs/myorg/myrepo/refs/master/something.txt
  scm/driver/fake/test_data/test_refs/myorg/myrepo/refs/mybranch/something.txt
Labels: approved, lgtm, size/M

#175 feat: Add milestone API
  scm/client.go
  scm/driver/bitbucket/bitbucket.go
  scm/driver/bitbucket/issue.go
  scm/driver/bitbucket/milestone.go
  scm/driver/fake/issue.go
  scm/driver/fake/pr.go
  scm/driver/gitea/gitea.go
  scm/driver/gitea/issue.go
  scm/driver/gitea/issue_test.go
  scm/driver/gitea/milestone.go
  scm/driver/gitea/milestone_test.go
  scm/driver/gitea/testdata/issue_clear_milestone.json
  scm/driver/gitea/testdata/issue_set_milestone.json
  scm/driver/gitea/testdata/milestone.json
  scm/driver/gitea/testdata/milestone.json.golden
  scm/driver/gitea/testdata/milestone_create.json
  scm/driver/gitea/testdata/milestones.json
  scm/driver/gitea/testdata/milestones.json.golden
  scm/driver/github/github.go
  scm/driver/github/issue.go
  scm/driver/github/issue_test.go
  scm/driver/github/milestone.go
  scm/driver/github/milestone_test.go
  scm/driver/github/pr.go
  scm/driver/github/testdata/issue_clear_milestone.json
  scm/driver/github/testdata/issue_set_milestone.json
  scm/driver/github/testdata/milestone.json
  scm/driver/github/testdata/milestone.json.golden
  scm/driver/github/testdata/milestone_create.json
  scm/driver/github/testdata/milestones.json
  scm/driver/github/testdata/milestones.json.golden
  scm/driver/github/util.go
  scm/driver/gitlab/gitlab.go
  scm/driver/gitlab/issue.go
  scm/driver/gitlab/issue_test.go
  scm/driver/gitlab/milestone.go
  scm/driver/gitlab/milestone_test.go
  scm/driver/gitlab/pr.go
  scm/driver/gitlab/pr_test.go
  scm/driver/gitlab/testdata/issue_or_pr_clear_milestone.json
  scm/driver/gitlab/testdata/issue_or_pr_set_milestone.json
  scm/driver/gitlab/testdata/milestone.json
  scm/driver/gitlab/testdata/milestone.json.golden
  scm/driver/gitlab/testdata/milestone_create.json
  scm/driver/gitlab/testdata/milestone_update.json
  scm/driver/gitlab/testdata/milestones.json
  scm/driver/gitlab/testdata/milestones.json.golden
  scm/driver/gitlab/util.go
  scm/driver/gogs/gogs.go
  scm/driver/gogs/issue.go
  scm/driver/gogs/milestone.go
  scm/driver/gogs/pr.go
  scm/driver/stash/issue.go
  scm/driver/stash/milestone.go
  scm/driver/stash/pr.go
  scm/driver/stash/stash.go
  scm/issue.go
  scm/milestone.go
  scm/pr.go
Labels: approved, size/XXL

#177 chore: add DeleteRef to gitea
  scm/driver/gitea/git.go
Labels: approved, lgtm, size/XS

#178 chore: return an error when deleting a branch returns false (gitea)
  scm/driver/gitea/git.go
Labels: approved, lgtm, size/XS

#176 fix: Paginate for lookup-by-listing GitLab functions
  scm/driver/gitlab/gitlab_test.go
  scm/driver/gitlab/org.go
  scm/driver/gitlab/repo.go
  scm/driver/gitlab/repo_test.go
  scm/driver/gitlab/user.go
Labels: approved, size/L

#179 fix: Trim `heads/` from gitea DeleteRef
  scm/driver/gitea/git.go
Labels: approved, lgtm, size/XS

#180 fix: Proper pagination in Gitea
  go.mod
  go.sum
  scm/client.go
  scm/driver/gitea/content.go
  scm/driver/gitea/content_test.go
  scm/driver/gitea/git.go
  scm/driver/gitea/git_test.go
  scm/driver/gitea/gitea.go
  scm/driver/gitea/gitea_test.go
  scm/driver/gitea/issue.go
  scm/driver/gitea/issue_test.go
  scm/driver/gitea/milestone.go
  scm/driver/gitea/milestone_test.go
  scm/driver/gitea/org.go
  scm/driver/gitea/org_test.go
  scm/driver/gitea/pr.go
  scm/driver/gitea/pr_test.go
  scm/driver/gitea/repo.go
  scm/driver/gitea/repo_test.go
  scm/driver/gitea/review.go
  scm/driver/gitea/review_test.go
  scm/driver/gitea/testdata/review_create.json
  scm/driver/gitea/user.go
  scm/driver/gitea/user_test.go
  scm/driver/gitea/webhook.go
  scm/driver/github/milestone_test.go
  scm/driver/github/org_test.go
  scm/driver/gitlab/milestone_test.go
  scm/user.go
Labels: approved, lgtm, size/XL

#181 feat: Implement a few more Gitea functions
  scm/driver/gitea/git.go
  scm/driver/gitea/git_test.go
  scm/driver/gitea/org.go
  scm/driver/gitea/repo.go
  scm/driver/gitea/testdata/commit.json
  scm/driver/gitea/testdata/commit.json.golden
  scm/driver/gitea/testdata/commits.json
  scm/driver/gitea/testdata/commits.json.golden
  scm/driver/gitea/testdata/tags.json
  scm/driver/gitea/testdata/tags.json.golden
Labels: approved, size/L

#183 feat: add delete repo support
  scm/driver/bitbucket/repo.go
  scm/driver/fake/repo.go
  scm/driver/gitea/repo.go
  scm/driver/github/repo.go
  scm/driver/gitlab/repo.go
  scm/driver/gogs/repo.go
  scm/driver/stash/repo.go
  scm/repo.go
Labels: approved, lgtm, size/M

#184 feat: add factory with basic auth
  scm/driver/gitea/gitea.go
  scm/factory/factory.go
Labels: approved, lgtm, size/M

#185 feat: add Create/Delete organization
  scm/driver/bitbucket/org.go
  scm/driver/fake/org.go
  scm/driver/gitea/org.go
  scm/driver/github/org.go
  scm/driver/gitlab/org.go
  scm/driver/gogs/org.go
  scm/driver/stash/org.go
  scm/org.go
Labels: approved, lgtm, size/M

#186 feat: add CreateToken/DeleteToken for users
  scm/driver/bitbucket/user.go
  scm/driver/fake/user.go
  scm/driver/gitea/user.go
  scm/driver/github/user.go
  scm/driver/gitlab/user.go
  scm/driver/gogs/user.go
  scm/driver/stash/user.go
  scm/user.go
Labels: approved, lgtm, size/M

#187 feat: implement list and accept pending organization invites for github
  scm/driver/bitbucket/org.go
  scm/driver/fake/org.go
  scm/driver/gitea/org.go
  scm/driver/github/org.go
  scm/driver/github/org_test.go
  scm/driver/github/testdata/list_pending_invitations.json
  scm/driver/github/testdata/org_accept_invitation.json
  scm/driver/gitlab/org.go
  scm/driver/gogs/org.go
  scm/driver/stash/org.go
  scm/org.go
Labels: approved, lgtm, size/L

#188 feat: implement list organisation memberships for the authenticated user
  scm/driver/bitbucket/org.go
  scm/driver/fake/org.go
  scm/driver/gitea/org.go
  scm/driver/github/org.go
  scm/driver/github/org_test.go
  scm/driver/github/testdata/list_memberships.json
  scm/driver/gitlab/org.go
  scm/driver/gogs/org.go
  scm/driver/stash/org.go
  scm/org.go
Labels: approved, lgtm, size/L
