Repository jenkins-x/go-scm, pull requests merged in 2020-02, with the labels that each got.

#71 fix: Add tests and fix for the GitLab client.
  scm/driver/gitlab/gitlab.go
  scm/driver/gitlab/gitlab_test.go
Labels: approved, lgtm, ok-to-test, size/L

#74 fix: add a Repositories.Create() function
  scm/content.go
  scm/driver/bitbucket/repo.go
  scm/driver/fake/data.go
  scm/driver/fake/repo.go
  scm/driver/gitea/repo.go
  scm/driver/github/repo.go
  scm/driver/github/repo_test.go
  scm/driver/github/testdata/repo_create.json
  scm/driver/github/testdata/repo_create.json.golden
  scm/driver/gitlab/repo.go
  scm/driver/gogs/repo.go
  scm/driver/stash/repo.go
  scm/repo.go
Labels: approved, lgtm, size/L

#75 fix: add support for the users API on the fake provider
  scm/driver/fake/data.go
  scm/driver/fake/fake.go
  scm/driver/fake/repo.go
  scm/driver/fake/user.go
Labels: approved, lgtm, size/L

#77 fix: add support for a Deployments API
  README.md
  scm/client.go
  scm/deploy.go
  scm/driver/fake/repo.go
  scm/driver/github/deploy.go
  scm/driver/github/deploy_test.go
  scm/driver/github/github.go
  scm/driver/github/repo.go
  scm/driver/github/testdata/deploy.json
  scm/driver/github/testdata/deploy.json.golden
  scm/driver/github/testdata/deploy_create.json
  scm/driver/github/testdata/deploy_create.json.golden
  scm/driver/github/testdata/deploy_status.json
  scm/driver/github/testdata/deploy_status.json.golden
  scm/driver/github/testdata/deploy_status_create.json
  scm/driver/github/testdata/deploy_status_create.json.golden
  scm/driver/github/testdata/deploy_statuses.json
  scm/driver/github/testdata/deploy_statuses.json.golden
  scm/driver/github/testdata/deploys.json
  scm/driver/github/testdata/deploys.json.golden
  scm/driver/github/user.go
Labels: approved, lgtm, size/XL

#76 feat: Move internal/hmac to pkg/
  pkg/hmac/hmac.go
  pkg/hmac/hmac_test.go
  scm/driver/gitea/webhook.go
  scm/driver/github/webhook.go
  scm/driver/gogs/webhook.go
  scm/driver/stash/webhook.go
Labels: approved, lgtm, ok-to-test, size/XS
