Repository jenkins-x/go-scm, pull requests merged in 2020-10, with the labels that each got.

#190 fix: gitlab use oldrev field on merge request hook in pullRequestHook.changes
  scm/driver/gitlab/testdata/webhooks/pull_request_edited.json
  scm/driver/gitlab/testdata/webhooks/pull_request_edited.json.golden
  scm/driver/gitlab/webhook.go
Labels: approved, lgtm, ok-to-test, size/S

#191 feat: Add squash options to PullRequest merge for Gitlab
  scm/driver/gitlab/pr.go
  scm/driver/gitlab/util.go
  scm/pr.go
Labels: approved, lgtm, ok-to-test, size/S

#192 fix: `json: cannot unmarshall array into Go value of type gitlab.gl_name`
  scm/driver/gitlab/gitlab.go
Labels: approved, lgtm, ok-to-test, size/M

#193 fix: Handle GitLab namespace query as an array properly
  scm/driver/gitlab/gitlab.go
  scm/driver/gitlab/testdata/find_namespace.json
Labels: approved, size/L

#194 fix: Populate base repo in GitLab PRs
  scm/driver/gitlab/pr.go
  scm/driver/gitlab/repo.go
  scm/driver/gitlab/testdata/merge.json.golden
  scm/driver/gitlab/testdata/merges.json.golden
  scm/driver/gitlab/testdata/pr_create.json.golden
Labels: approved, lgtm, size/M

#195 fix: gitlab add ability to list files
  scm/driver/gitlab/content.go
Labels: approved, lgtm, ok-to-test, size/M

#197 fix: add unit test for listing contents with gitlab
  scm/driver/gitlab/content_test.go
  scm/driver/gitlab/testdata/content_list.json
  scm/driver/gitlab/testdata/content_list.json.golden
Labels: approved, lgtm, size/L

#198 fix: improve fake support for invitations
  scm/driver/fake/content_test.go
  scm/driver/fake/data.go
  scm/driver/fake/repo.go
  scm/driver/fake/user.go
  scm/driver/fake/user_test.go
Labels: approved, lgtm, size/L

#200 chore: Add fmt/lint/vet/sec checks
  Makefile
  jenkins-x.yml
  pkg/hmac/hmac.go
  scm/app.go
  scm/client.go
  scm/const.go
  scm/driver/bitbucket/bitbucket.go
  scm/driver/bitbucket/git.go
  scm/driver/bitbucket/org.go
  scm/driver/bitbucket/pr.go
  scm/driver/bitbucket/repo.go
  scm/driver/fake/content.go
  scm/driver/fake/data.go
  scm/driver/fake/org.go
  scm/driver/fake/repo.go
  scm/driver/fake/user.go
  scm/driver/gitea/gitea.go
  scm/driver/gitea/webhook.go
  scm/driver/github/github.go
  scm/driver/github/user_test.go
  scm/driver/github/webhook.go
  scm/driver/gitlab/content.go
  scm/driver/gitlab/git.go
  scm/driver/gitlab/gitlab.go
  scm/driver/gitlab/pr.go
  scm/driver/gitlab/webhook.go
  scm/driver/gogs/gogs.go
  scm/driver/gogs/webhook.go
  scm/driver/stash/stash.go
  scm/driver/stash/user.go
  scm/driver/stash/webhook.go
  scm/example_test.go
  scm/factory/examples/graphql/main.go
  scm/factory/factory.go
  scm/milestone.go
  scm/org.go
  scm/pr.go
  scm/review.go
  scm/transport/oauth1/oauth1.go
  scm/transport/oauth1/sign.go
  scm/util.go
  scm/util_test.go
  scm/webhook.go
Labels: approved, size/XL

#201 fix: add support for delete repository on github
  scm/driver/github/repo.go
Labels: approved, lgtm, size/XS

#202 fix: Add support for review hooks
  scm/driver/gitea/repo.go
  scm/driver/gitea/repo_test.go
  scm/driver/gitea/testdata/webhooks/review_approved.json
  scm/driver/gitea/testdata/webhooks/review_approved.json.golden
  scm/driver/gitea/webhook.go
  scm/driver/gitea/webhook_test.go
  scm/driver/github/repo.go
  scm/repo.go
Labels: approved, lgtm, size/L

#203 fix: implement pr.assignIssue in fake driver
  scm/driver/fake/pr.go
Labels: approved, lgtm, ok-to-test, size/S
