Repository jenkins-x/go-scm, pull requests merged in 2020-06, with the labels that each got.

#146 fix: list user private repos
  scm/driver/github/repo.go
Labels: approved, lgtm, size/S

#148 feat: Add updating of files to GitLab.
  scm/driver/gitlab/content.go
  scm/driver/gitlab/content_test.go
  scm/driver/gitlab/testdata/content_update.json
Labels: approved, lgtm, size/M

#150 fix: add support for Status.Link
  scm/driver/bitbucket/repo.go
  scm/driver/bitbucket/repo_test.go
  scm/driver/bitbucket/testdata/status.json.golden
  scm/driver/bitbucket/testdata/statuses.json.golden
  scm/driver/github/repo.go
  scm/driver/github/testdata/combined_status.json.golden
  scm/driver/github/testdata/status.json.golden
  scm/driver/github/testdata/statuses.json.golden
  scm/factory/examples/changes/main.go
  scm/factory/examples/commits/main.go
  scm/repo.go
Labels: approved, lgtm, size/L

#151 fix: add DiffLink to PullRequest
  scm/driver/bitbucket/pr.go
  scm/driver/bitbucket/testdata/pulls.json.golden
  scm/driver/github/integration/pr_test.go
  scm/driver/github/pr.go
  scm/driver/github/testdata/pr.json.golden
  scm/driver/github/testdata/pr_create.json.golden
  scm/driver/github/testdata/pulls.json.golden
  scm/driver/github/testdata/webhooks/pr_closed.json.golden
  scm/driver/github/testdata/webhooks/pr_comment.json.golden
  scm/driver/github/testdata/webhooks/pr_edited.json.golden
  scm/driver/github/testdata/webhooks/pr_labeled.json.golden
  scm/driver/github/testdata/webhooks/pr_opened.json.golden
  scm/driver/github/testdata/webhooks/pr_ready_for_review.json.golden
  scm/driver/github/testdata/webhooks/pr_reopened.json.golden
  scm/driver/github/testdata/webhooks/pr_review_submitted.json.golden
  scm/driver/github/testdata/webhooks/pr_sync.json.golden
  scm/driver/github/testdata/webhooks/pr_unlabeled.json.golden
  scm/pr.go
Labels: approved, lgtm, size/M

#149 fix: github: add sha parameter for listing commits
  scm/driver/github/integration/git_test.go
  scm/driver/github/util.go
  scm/example_test.go
  scm/git.go
Labels: approved, lgtm, ok-to-test, size/M
