Repository jenkins-x/go-scm, pull requests merged in 2020-01, with the labels that each got.

#61 fix: add API to query repos for a user or organisation
  scm/driver/bitbucket/repo.go
  scm/driver/fake/repo.go
  scm/driver/gitea/repo.go
  scm/driver/github/repo.go
  scm/driver/gitlab/repo.go
  scm/driver/gogs/repo.go
  scm/driver/stash/repo.go
  scm/factory/examples/repos/main.go
  scm/repo.go
Labels: approved, size/L

#62 Include PullRequestBranch data in GitLab responses.
  go.mod
  scm/driver/gitlab/pr.go
  scm/driver/gitlab/pr_test.go
  scm/driver/gitlab/testdata/merge.json.golden
  scm/driver/gitlab/testdata/merges.json
  scm/driver/gitlab/testdata/merges.json.golden
Labels: approved, lgtm, ok-to-test, size/M

#64 fix: add Christie and Billy to the owners file
  OWNERS
Labels: approved, lgtm, size/XS

#65 chore: Fake PR apis should behave like fake issue APIs
  OWNERS
  scm/driver/fake/data.go
  scm/driver/fake/pr.go
Labels: approved, lgtm, size/L

#66 fix: add an API for listing files in a repository
  scm/content.go
  scm/driver/bitbucket/content.go
  scm/driver/gitea/content.go
  scm/driver/github/content.go
  scm/driver/github/content_test.go
  scm/driver/github/testdata/content_list.json
  scm/driver/github/testdata/content_list.json.golden
  scm/driver/gitlab/content.go
  scm/driver/gogs/content.go
  scm/driver/stash/content.go
  scm/factory/examples/contentlist/main.go
  scm/factory/examples/contents/main.go
Labels: approved, lgtm, size/L

#63 feat: Add support for creating PullRequests.
  scm/driver/bitbucket/pr.go
  scm/driver/bitbucket/pr_test.go
  scm/driver/fake/data.go
  scm/driver/fake/pr.go
  scm/driver/gitea/pr.go
  scm/driver/gitea/pr_test.go
  scm/driver/github/pr.go
  scm/driver/github/pr_test.go
  scm/driver/github/testdata/pr_create.json
  scm/driver/github/testdata/pr_create.json.golden
  scm/driver/gitlab/pr.go
  scm/driver/gitlab/pr_test.go
  scm/driver/gitlab/testdata/pr_create.json
  scm/driver/gitlab/testdata/pr_create.json.golden
  scm/driver/gogs/pr.go
  scm/driver/gogs/pr_test.go
  scm/driver/stash/pr.go
  scm/driver/stash/pr_test.go
  scm/pr.go
Labels: approved, lgtm, ok-to-test, size/XXL

#67 feat: Record the create pull request in the fake driver.
  scm/driver/fake/pr.go
Labels: approved, lgtm, ok-to-test, size/XS
