Repository jenkins-x/go-scm, pull requests merged in 2021-03, with the labels that each got.

#241 Fix Creation of Git Deployment from the module
  scm/driver/github/deploy.go
Labels: approved, lgtm, ok-to-test, size/S

#242 fix: gitlab pushHook, add after field from webhook
  scm/driver/gitlab/testdata/webhooks/branch_create.json.golden
  scm/driver/gitlab/testdata/webhooks/push.json.golden
  scm/driver/gitlab/testdata/webhooks/tag_create.json.golden
  scm/driver/gitlab/webhook.go
Labels: approved, lgtm, ok-to-test, size/XS

#244 fix: add a number of bitbucket server fixes
  scm/driver/stash/issue.go
  scm/driver/stash/repo.go
  scm/driver/stash/testdata/webhooks/push.json.golden
  scm/driver/stash/webhook.go
  scm/factory/examples/prlabel/main.go
Labels: approved, lgtm, size/M

#245 feat: add webhook PR action converted_to_draft
  scm/const.go
  scm/driver/github/testdata/webhooks/pr_converted_to_draft.json
  scm/driver/github/testdata/webhooks/pr_converted_to_draft.json.golden
  scm/driver/github/webhook.go
  scm/driver/github/webhook_test.go
Labels: approved, lgtm, ok-to-test, size/XL

#246 fix: add a fake deployments implementation
  scm/driver/fake/data.go
  scm/driver/fake/deploy.go
  scm/driver/fake/deploy_test.go
  scm/driver/fake/fake.go
  scm/driver/github/deploy.go
  scm/driver/github/deploy_test.go
Labels: approved, lgtm, size/L

#247 fix: add support for creating repositories
  scm/client.go
  scm/driver/bitbucket/repo.go
  scm/driver/fake/deploy.go
  scm/driver/fake/deploy_test.go
  scm/driver/github/deploy.go
  scm/driver/gitlab/webhook.go
  scm/factory/factory.go
Labels: approved, lgtm, size/L

#251 fix: improve bitbucket cloud webhooks
  scm/driver/bitbucket/repo.go
  scm/driver/bitbucket/repo_test.go
Labels: approved, lgtm, size/M

#254 fix: improve the webhook parsing for bitbucket cloud
  scm/driver/bitbucket/git.go
  scm/driver/bitbucket/issue.go
  scm/driver/bitbucket/pr.go
  scm/driver/bitbucket/testdata/webhooks/pr_created.json.golden
  scm/driver/bitbucket/testdata/webhooks/pr_declined.json.golden
  scm/driver/bitbucket/testdata/webhooks/pr_fulfilled.json.golden
  scm/driver/bitbucket/testdata/webhooks/pr_updated.json.golden
  scm/driver/bitbucket/testdata/webhooks/push.json.golden
  scm/driver/bitbucket/testdata/webhooks/push_branch_create.json.golden
  scm/driver/bitbucket/testdata/webhooks/push_tag_create.json.golden
  scm/driver/bitbucket/webhook.go
Labels: approved, lgtm, size/XXL

#253 Set the is_private flag to true
  scm/driver/bitbucket/repo.go
Labels: approved, lgtm, size/XS

#255 fix: change Private to bool
  scm/driver/bitbucket/pr.go
  scm/driver/bitbucket/pr_test.go
  scm/driver/bitbucket/repo.go
Labels: size/XS

#257 fix: refactor the label comment code
  scm/driver/bitbucket/issue.go
  scm/driver/bitbucket/pr.go
  scm/driver/stash/issue.go
  scm/driver/stash/pr.go
  scm/labels/labels.go
Labels: approved, lgtm, size/L

#259 fix: added bitbucket cloud comment support
  scm/client.go
  scm/driver/bitbucket/issue.go
  scm/driver/bitbucket/issue_test.go
  scm/driver/bitbucket/pr.go
  scm/driver/bitbucket/repo.go
  scm/driver/bitbucket/util.go
  scm/factory/examples/combinedstatus/main.go
Labels: approved, lgtm, size/L

#262 fix: disable the gitea delete test for now
  scm/driver/gitea/content_test.go
Labels: approved, size/XS

#261 feat: create hooks with deployment events
  scm/driver/github/repo.go
  scm/driver/github/repo_test.go
  scm/repo.go
Labels: approved, lgtm, size/S
