Repository jenkins-x/go-scm, pull requests merged in 2021-01, with the labels that each got.

#216 fix: implement PullRequests.List for fake
  scm/driver/fake/pr.go
Labels: approved, lgtm, size/M

#219 feat: added support for bitbucket server organisation listing
  scm/driver/stash/org.go
  scm/driver/stash/org_test.go
  scm/driver/stash/stash_test.go
  scm/driver/stash/testdata/orgs.json
  scm/driver/stash/testdata/orgs.json.golden
Labels: approved, lgtm, ok-to-test, size/L

#221 fix: better fake handling of labels on PRs
  scm/driver/fake/pr.go
Labels: approved, lgtm, size/S

#220 feat: added status responses to find fake repository functionality to…
  scm/driver/fake/repo.go
Labels: approved, lgtm, ok-to-test, size/XS

#222 feat: add support for labels as comments for bitbucket server
  scm/driver/stash/pr.go
  scm/driver/stash/pr_test.go
  scm/driver/stash/testdata/pr_label_comment.json
  scm/driver/stash/testdata/pr_label_comments.json
  scm/driver/stash/testdata/pr_labels.json.golden
Labels: approved, lgtm, ok-to-test, size/L

#223 fix: resolved incorrect API call when adding collaborator in bitbucke…
  scm/driver/stash/repo.go
  scm/driver/stash/repo_test.go
Labels: approved, lgtm, ok-to-test, size/XS

#224 feat: provide dummy invite support for bitbucket server
  scm/driver/stash/user.go
  scm/driver/stash/user_test.go
Labels: approved, lgtm, ok-to-test, size/S

#225 fix: updated admin permission for gitlab to be maintainer for better …
  scm/driver/gitlab/repo.go
Labels: approved, lgtm, ok-to-test, size/XS

#226 feat: implement gitea driver release api
  go.mod
  go.sum
  scm/driver/gitea/gitea.go
  scm/driver/gitea/release.go
  scm/driver/gitea/release_test.go
  scm/driver/gitea/testdata/release.json
  scm/driver/gitea/testdata/release.json.golden
  scm/driver/gitea/testdata/release_create.json
  scm/driver/gitea/testdata/release_update.json
  scm/driver/gitea/testdata/releases.json
  scm/driver/gitea/testdata/releases.json.golden
Labels: approved, lgtm, ok-to-test, size/L

#227 Gitea release user doesnt exist workaround
  scm/driver/gitea/release.go
  scm/factory/examples/release/get.go
Labels: approved, lgtm, ok-to-test, size/M

#228 fix: need to also return a 404 not found go error in the workaround
  scm/driver/gitea/release.go
Labels: approved, lgtm, ok-to-test

#229 fix: sometimes gitea returns an empty error message with 500 status code so handle that as missing release
  scm/driver/gitea/release.go
Labels: approved, lgtm, ok-to-test, size/XS

#230 fix: gitea FindByTag workaround
  scm/driver/gitea/release.go
Labels: approved, lgtm, ok-to-test, size/M

#231 fix: generate release link instead of using the API link that gitea provides
  scm/driver/gitea/release.go
  scm/driver/gitea/release_test.go
  scm/driver/gitea/testdata/release.json
  scm/driver/gitea/testdata/release.json.golden
  scm/driver/gitea/testdata/releases.json
  scm/driver/gitea/testdata/releases.json.golden
Labels: approved, ok-to-test, size/M

#232 fix: deployment/deployment_status webhooks implementation
  scm/deploy.go
  scm/driver/github/deploy.go
  scm/driver/github/integration/issue_test.go
  scm/driver/github/integration/org_test.go
  scm/driver/github/integration/pr_test.go
  scm/driver/github/integration/user_test.go
  scm/driver/github/testdata/deploy.json.golden
  scm/driver/github/testdata/deploy_create.json.golden
  scm/driver/github/testdata/deploys.json.golden
  scm/driver/github/testdata/webhooks/deployment.json.golden
  scm/driver/github/testdata/webhooks/deployment_status.json.golden
  scm/driver/github/webhook.go
  scm/webhook.go
Labels: approved, lgtm, ok-to-test, size/L
