Repository jenkins-x/go-scm, pull requests merged in 2021-07, with the labels that each got.

#289 Fix Bitbucket IsCollaborator api
  scm/driver/bitbucket/pr.go
  scm/driver/bitbucket/repo.go
  scm/driver/bitbucket/testdata/pr_create.json.golden
  scm/driver/bitbucket/testdata/pulls.json.golden
  scm/driver/bitbucket/user.go
  scm/driver/bitbucket/webhook.go
Labels: approved, lgtm, ok-to-test, size/M

#290 fix: add omitempty
  scm/driver/github/review.go
Labels: approved, lgtm, ok-to-test, size/XS

#291 fix: add back /all for gitlab
  scm/driver/gitlab/org.go
  scm/driver/gitlab/repo.go
  scm/driver/gitlab/repo_test.go
Labels: approved, size/S

#293 fix: Initialize merge state attributes of PR for BBC
  scm/driver/bitbucket/pr.go
Labels: approved, lgtm, ok-to-test, size/M

#294 fix: add support for polling webhooks
  scm/driver/gitlab/testdata/webhooks/push2.json
  scm/driver/gitlab/testdata/webhooks/push2.json.golden
  scm/driver/gitlab/webhook_test.go
  scm/test_data/webhooks/push.json
  scm/webhook.go
  scm/webhook_test.go
Labels: approved, size/XL

#295 fix: error fetching sha for branch name with slash in it
  scm/driver/bitbucket/git.go
  scm/driver/bitbucket/testdata/webhooks/pr_created_slashbranch.json
  scm/driver/bitbucket/testdata/webhooks/pr_created_slashbranch.json.golden
  scm/driver/bitbucket/webhook_test.go
Labels: approved, lgtm, ok-to-test, size/L

#296 fix: initialize CombinedStatus with computed combined state value (BBC)
  scm/driver/bitbucket/repo.go
Labels: approved, lgtm, ok-to-test, size/XS
