Repository jenkins-x/go-scm, pull requests merged in 2021-05, with the labels that each got.

#280 feat: add 2-leg oauth flow for bitbucket cloud
  scm/factory/factory.go
Labels: approved, lgtm, ok-to-test, size/S

#281 feat: get missing pr info for issue comment hook from gitea
  scm/driver/gitea/pr.go
  scm/driver/gitea/testdata/webhooks/pull_request_comment_created.json.golden
  scm/driver/gitea/testdata/webhooks/pull_request_comment_created_pr.json
  scm/driver/gitea/webhook.go
  scm/driver/gitea/webhook_test.go
Labels: approved, ok-to-test, size/L

#282 fix: lets add ga go mod tidy to the PR generation
  .jx/updatebot.yaml
Labels: approved, size/XS
