Repository jenkins-x/go-scm, pull requests merged in 2021-02, with the labels that each got.

#234 fix: use gitea sdk fork direclty via import instead of replace
  go.mod
  scm/driver/gitea/content.go
  scm/driver/gitea/git.go
  scm/driver/gitea/gitea.go
  scm/driver/gitea/issue.go
  scm/driver/gitea/milestone.go
  scm/driver/gitea/org.go
  scm/driver/gitea/pr.go
  scm/driver/gitea/release.go
  scm/driver/gitea/repo.go
  scm/driver/gitea/review.go
  scm/driver/gitea/user.go
  scm/driver/gitea/webhook.go
Labels: approved, lgtm, ok-to-test, size/S

#235 fix: Update Gitlab Webhook Service to Fetch Users By ID
  go.mod
  scm/driver/gitlab/gitlab.go
  scm/driver/gitlab/user.go
  scm/driver/gitlab/webhook.go
  scm/driver/gitlab/webhook_test.go
Labels: approved, lgtm, ok-to-test, size/L

#236 chore: update gitea replace ref
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test, size/XS

#237 feat: back to using import from gitea directly, update tests for new api fields
  go.mod
  go.sum
  scm/driver/gitea/content.go
  scm/driver/gitea/content_test.go
  scm/driver/gitea/git.go
  scm/driver/gitea/gitea.go
  scm/driver/gitea/issue.go
  scm/driver/gitea/milestone.go
  scm/driver/gitea/org.go
  scm/driver/gitea/pr.go
  scm/driver/gitea/release.go
  scm/driver/gitea/repo.go
  scm/driver/gitea/review.go
  scm/driver/gitea/testdata/assign_issue.json
  scm/driver/gitea/testdata/close_issue.json
  scm/driver/gitea/testdata/issue_clear_milestone.json
  scm/driver/gitea/testdata/issue_set_milestone.json
  scm/driver/gitea/testdata/reopen_issue.json
  scm/driver/gitea/testdata/unassign_issue.json
  scm/driver/gitea/user.go
  scm/driver/gitea/webhook.go
Labels: approved, lgtm, ok-to-test, size/M

#238 fix: tidy modules
  go.mod
  go.sum
Labels: approved, size/S

#239 chore: upgrade to latest gitea commit
  go.mod
  go.sum
Labels: approved, size/S
