Repository jenkins-x/go-scm, pull requests merged in 2022-09, with the labels that each got.

#340 fix: unable to build locally
  go.mod
  go.sum
Labels: size/XS, approved

#343 Add Repositories.Delete method for GitLab driver
  scm/driver/gitlab/repo.go
  scm/driver/gitlab/repo_test.go
Labels: approved, size/S, ok-to-test, lgtm

#342 chore: adding dependabot config
  .github/dependabot.yml
Labels: size/XS, approved

#349 chore(deps): bump transient dependency protobuf
  go.mod
  go.sum
Labels: size/XS, approved

#350 fix: fix failing lighthouse builds
  scm/driver/azure/webhook.go
  scm/driver/github/issue.go
  scm/driver/github/issue_test.go
  scm/driver/github/testdata/issue_search.json.golden
  scm/driver/github/testdata/webhooks/issue_comment.json.golden
  scm/driver/github/webhook_test.go
  scm/issue.go
  scm/webhook.go
Labels: approved, size/S, lgtm
