Repository jenkins-x/go-scm, pull requests merged in 2022-11, with the labels that each got.

#351 chore: improve azure integration tests
  scm/driver/azure/integration/pr_test.go
  scm/driver/azure/pr.go
  scm/example_test.go
Labels: approved, size/M

#358 feat: Improvements on fake
  scm/driver/fake/pr.go
Labels: size/XS, approved

#359 chore: Upgrade go version to 1.19 and golangci lint to 1.50.1
  .golangci.yml
  go.mod
  hack/linter.sh
Labels: size/XS, approved, ok-to-test
