Repository jenkins-x/go-scm, pull requests merged in 2022-06, with the labels that each got.

#332 chore: Update OWNERS and OWNERS_ALIASES
  OWNERS
  OWNERS_ALIASES
Labels: approved, size/M

#333 fix: add Sort option
  scm/client.go
  scm/driver/gitlab/util.go
  scm/driver/gitlab/util_test.go
Labels: size/XS, approved, ok-to-test

#335 fix: Don't remove existing values for release
  scm/driver/github/release.go
Labels: size/XS, approved
