Repository jenkins-x/go-scm, pull requests merged in 2023-08, with the labels that each got.

#404 fix: correct path response for fake content
  scm/driver/fake/content.go
Labels: size/XS, approved, lgtm

#402 fix: use gitea admin
  scm/driver/gitea/testdata/issue.json.golden
  scm/driver/gitea/user.go
Labels: approved, size/S

#299 gitlab: AddCollaborator tell when user is a member
  scm/driver/gitlab/repo.go
Labels: size/XS, approved, ok-to-test
