Repository jenkins-x/go-scm, pull requests merged in 2025-07, with the labels that each got.

#500 feat: log details of failed github req/res
  scm/driver/github/github.go
Labels: approved, size/S

#503 fix: mock all requests to gitea
  scm/driver/gitea/git_test.go
  scm/driver/gitea/issue_test.go
Labels: approved, size/S

#489 feat: handle webhook event pr:deleted for stash
  .golangci.yml
  .lighthouse/jenkins-x/lint.yaml
  .lighthouse/jenkins-x/pullrequest.yaml
  .lighthouse/jenkins-x/release.yaml
  scm/driver/stash/testdata/webhooks/pr_deleted.json.golden
  scm/driver/stash/webhook.go
  scm/driver/stash/webhook_test.go
Labels: approved, size/L, ok-to-test

#501 fix: log details of failed github req/res with level warn
  scm/driver/github/github.go
Labels: size/XS, approved
